name: Python application

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Make README.md
        run: python3 make-readme.py
      
      - name: Add and commit
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          mv README.md README_.md
          git checkout master
          mv README_.md README.md
          git add README.md
          git commit -m "update" -a
          git push origin master
