name: Deploy to Github Pages

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Make README.md
        run: |
          python3 make-readme.py
          mkdir public
          cp README.md ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          disable_nojekyll: true
