name: Python application

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Make README.md
        run: |
          python3 make-readme.py
          mkdir public
          cp README.md ./public
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
