name: Python application

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Make README.md
        run: python3 make-readme.py
      
      - name: push
        uses: dciborow/commit@0.0.2
        with:
          push-branch: master
          commit-message: update
          force-add: true
          force-push: true
          files: README.md
          name: github-actions
          email: actions@github.com
